### ISSUE TITLE
Ability to access the state from the component

### ISSUE THREAD

**Issue by avikraman** [Celtian/ngx-suspense-of#15]
It'll be great if we could access the directive state.
The reason I ask is the subscribed value always need not be ready to be iterated.. What If it needs some transformation or refinement?
This is exactly what I would need.
I am not sure if there's a out of the box support for this already.

Any enhancements or insights would be greatly appreciated.

**Comment by Celtian** [comment]
I will take a look. Thank for feedback...

**Comment by Celtian** [comment]
https://github.com/Celtian/ngx-suspense-of/pull/17

**Comment by Celtian** [comment]
New input function for tracking state changes is now available.
